GET http://127.0.0.1:3000/categorias HTTP/1.1
Content-Type: application/json

###

POST http://127.0.0.1:3000/categorias HTTP/1.1
Content-Type: application/json

{
    "nome": "1231231235wdf"
}


###

DELETE http://127.0.0.1:3000/categorias/6550709a35d9d695698d0e33 HTTP/1.1


###

GET http://127.0.0.1:3000/salas HTTP/1.1

###
POST http://127.0.0.1:3000/salas HTTP/1.1
Content-Type: application/json

{
    "nome": "Salas teste 3",
    "categoria": "65507e4fc8f2135895bd9599"
}

###

GET http://127.0.0.1:3000/categorias/65507e4fc8f2135895bd9599/salas HTTP/1.1
Content-Type: application/json
